/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'acachiguango' at '20/04/18 15:37' with Gradle 2.14.1
 *
 * @author acachiguango, @date 20/04/18 15:37
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
